# Generated by Django 3.2.6 on 2021-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('slogan', models.CharField(max_length=40, verbose_name='Слоган')),
                ('align_choice', models.CharField(choices=[('left', 'по левому краю'), ('right', 'по правому краю'), ('center', 'по центру')], default='center', max_length=8, verbose_name='выравнивание')),
                ('image', models.ImageField(blank=True, upload_to='Advertising/', verbose_name='рекламный банер')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
                'ordering': ['created_at'],
            },
        ),
    ]
