# Generated by Django 3.2.6 on 2021-09-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'ordering': ['created_at'], 'verbose_name': 'Гараж', 'verbose_name_plural': 'Гаражи'},
        ),
        migrations.AlterModelOptions(
            name='landplot',
            options={'ordering': ['created_at'], 'verbose_name': 'Земельный участок', 'verbose_name_plural': 'Земельные участки'},
        ),
        migrations.AddField(
            model_name='garage',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена $'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garage',
            name='realtors',
            field=models.ManyToManyField(blank=True, to='agency.Realtor', verbose_name='Риелтор'),
        ),
        migrations.AddField(
            model_name='landplot',
            name='realtors',
            field=models.ManyToManyField(blank=True, to='agency.Realtor', verbose_name='Риелтор'),
        ),
    ]
