# Generated by Django 3.2.3 on 2021-08-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=17, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Риелтор',
                'verbose_name_plural': 'Риелторы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='apartment',
            name='realtor',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='agency.Realtor', verbose_name='Риелтор'),
        ),
    ]
