# Generated by Django 3.2.3 on 2021-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20210817_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='realtor',
            field=models.ManyToManyField(blank=True, related_name='realtors', to='agency.Realtor', verbose_name='Риелтор'),
        ),
    ]
