# Generated by Django 3.2.3 on 2021-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_apartment_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='realtor',
        ),
        migrations.AddField(
            model_name='apartment',
            name='realtors',
            field=models.ManyToManyField(blank=True, to='agency.Realtor', verbose_name='Риелтор'),
        ),
    ]
