# Generated by Django 3.2.6 on 2021-09-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20210926_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='image',
            field=models.ImageField(upload_to='Advertising/', verbose_name='рекламный банер'),
        ),
    ]
