# Generated by Django 3.2.6 on 2021-08-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20210817_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Поселок',
                'verbose_name_plural': 'Поселки',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['created_at'], 'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['created_at'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AddField(
            model_name='house',
            name='settlement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='agency.settlement', verbose_name='Поселок'),
        ),
    ]
