# Generated by Django 3.2.6 on 2021-09-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_advertising_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='slogan_color',
            field=models.CharField(default='#fafafa', max_length=7, verbose_name='Цвет слогана'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='title_color',
            field=models.CharField(default='#fafafa', max_length=7, verbose_name='Цвет заголовка'),
        ),
    ]
