# Generated by Django 3.2.6 on 2021-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20210821_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
    ]
