# Generated by Django 3.2.6 on 2021-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_alter_settlement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='realtors',
            field=models.ManyToManyField(blank=True, to='agency.Realtor', verbose_name='Риелтор'),
        ),
    ]
